services:
  db:
    image: postgres:16
    container_name: vado_postgres
    restart: unless-stopped
    env_file:
      - vado_app.env.prod
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vadmark -d vadodb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data   # том для сохранения БД
      - ./data:/app/data   # монтируем локальную папку внутрь контейнера
      - ./db/init:/docker-entrypoint-initdb.d # SQL-скрипты при старте
    networks:
      - vado-network

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # Изменено для Docker-сети
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092  # Изменено для Docker-сети
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - vado-network
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092" ]
      interval: 10s
      timeout: 10s
      retries: 5


  app:
    container_name: vado_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy # app ждет healthcheck БД
      kafka:
        condition: service_healthy
    env_file:
      - vado_app.env.prod
    volumes:
      - ./data/app:/app/data   # монтируем локальную папку внутрь контейнера
    ports:
      - "5555:5555"   # если приложение слушает веб-порт

volumes:
  db_data:
  kafka_data:

networks:
  vado-network:
    driver: bridge