#version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: vadmark
      POSTGRES_PASSWORD: 5125341
      POSTGRES_DB: vadodb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vadmark -d vadodb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data   # том для сохранения БД
      - ./data:/app/data   # монтируем локальную папку внутрь контейнера
      - ./db/init:/docker-entrypoint-initdb.d # SQL-скрипты при старте

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy # app ждет healthcheck БД
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: vadmark
      DB_PASSWORD: 5125341
      DB_NAME: vadodb
      APP_ENV: production
    volumes:
      - ./data:/app/data   # монтируем локальную папку внутрь контейнера
    ports:
      - "5555:5555"   # если приложение слушает веб-порт

volumes:
  db_data: