basePath: /
definitions:
  model.Task:
    description: Структура задачи.
    properties:
      completed:
        description: Флаг выполнения
        example: false
        type: boolean
      description:
        description: Описание задачи
        example: Купить 2 литра
        type: string
      id:
        description: Уникальный идентификатор
        example: 1
        format: int64
        type: integer
      name:
        description: Название задачи
        example: Купить молоко
        type: string
    type: object
host: localhost:5555
info:
  contact: {}
  description: Это REST API для задач.
  title: Vado API
  version: "1.0"
paths:
  /tasks:
    delete:
      description: Чистит список задач
      produces:
      - text/plain
      responses:
        "200":
          description: Delete tasks.
          schema:
            type: string
      summary: Удалить все задачи
      tags:
      - tasks
    get:
      description: Возвращает все задачи
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Task'
            type: array
      summary: Получить список задач.
      tags:
      - tasks
    post:
      consumes:
      - application/json
      description: Добавляет новую задачу
      parameters:
      - description: Task info
        in: body
        name: task
        required: true
        schema:
          $ref: '#/definitions/model.Task'
      produces:
      - text/plain
      responses:
        "200":
          description: Task created.
          schema:
            type: string
      summary: Создать задачу
      tags:
      - tasks
  /tasks/{id}:
    delete:
      description: Удаляет задачу по её ID
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Delete task {id}.
          schema:
            type: string
        "400":
          description: Invalid id
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
      summary: Удалить задачу по ID
      tags:
      - tasks
    get:
      description: Возвращает задачу по её ID
      parameters:
      - description: ID задачи
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Task'
        "400":
          description: Invalid id
          schema:
            type: string
        "404":
          description: Task not found
          schema:
            type: string
      summary: Получить задачу по ID
      tags:
      - tasks
swagger: "2.0"
