services:
  zookeeper:
    image: zookeeper:3.6.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  kafka-init:
    image: wurstmeister/kafka:latest
    depends_on:
      - kafka
    networks:
      - kafka-net
    entrypoint: >
      sh -c "sleep 15 && kafka-topics.sh --create --if-not-exists --zookeeper zookeeper:2181 --replication-factor 1 --partitions 1 --topic tasks"

networks:
  kafka-net:
    driver: bridge